# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c0f69862445be47dfea72cb4b13eb05be9c80477289768e5c52353bbaf4a76cd8f0252d1dc770488b6619d7e7014747d8bca11ab918a3e79d5336b59a64a214

test:
  secret_key_base: 4fa499fdb51e6c93663e6e47da8149becc11656d9aacab2c560a69b72a61c8417e16833d807c70953ef2f9aa15adb6c5e0cc3139fe38b04299336a4dd98befea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
